package com.carepulse.carepulse.enums;

public enum NotificationType {
    TICKET_CREE,
    NOUVEAU_TICKET,
    POSITION_UPDATE,
    RAPPEL_15MIN,
    RAPPEL_5MIN,
    APPEL_PATIENT,
    PATIENT_PRET,
    URGENCE_INSEREE,
    RETARD_GENERAL,
    NO_SHOW_ALERTE,
    TICKET_ANNULE,
    CONSULTATION_DEMARREE,
    CONSULTATION_TERMINEE,
    NOUVEAU_MESSAGE,
    ABSENCE_SIGNALEE,
    SURCHARGE_DETECTEE
}